@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
!startsub default
class KeyboardInteractEventProducer {
    + StartCapture(nativeK : INativeKeyboard) : void
    + StopCapture() : void
}
abstract class "DefaultEventQueue<T>" {
}
!endsub
"DefaultEventQueue<T>" "      <KeyboardInteractEvent>" <|-- KeyboardInteractEventProducer
@enduml
