@startuml ProcessCommand
skinparam monochrome true
skinparam classAttributeIconSize 0
hide empty fields

class ICLICommand {
    + ExecuteCommand(options: Options)
}

class ProcessOptions {
    + Input : string
    + Output : string
    + ProcessingEnabled: bool
    + Verbose: bool
}

class ProcessCommand {
    + ProcessCommand(recordingManager : IRecordingManager)
    + ExecuteCommand(options: ProcessOptions)
}

ProcessCommand ... ProcessOptions : uses
ICLICommand <.. ProcessCommand : implements
IRecordingManager <-- "receiver" ProcessCommand
IDecoder <-- "decoder" ProcessCommand
@enduml