@startuml ProcessOptions
skinparam monochrome true
skinparam classAttributeIconSize 0

class ProcessOptions {
    + Input : string
    + Output : string
    + ProcessingEnabled: bool
    + Verbose: bool
}

@enduml
