@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class MouseClickEvent {
    + HWnd : string <<get>> <<set>>
    + MouseAction : System.Windows.Input.MouseAction <<get>> <<set>>
}
abstract class MouseEvent {
    + MousePosition : System.Windows.Point <<get>> <<set>>
}
abstract class Event
!endsub
MouseEvent <|-- MouseClickEvent
Event <|-- MouseEvent

@enduml
