@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class MouseClickEvent {
    + HWnd : string <<get>> <<set>>
    + MouseAction : MouseAction <<get>> <<set>>
}
abstract class MouseEvent
abstract class Event
MouseEvent <|-- MouseClickEvent
Event <|-- MouseEvent

@enduml
