@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class MouseScrollEvent {
    + ScrollAmount : short <<get>> <<set>>
    + HWnd : string <<get>> <<set>>
}
abstract class MouseEvent
abstract class Event
MouseEvent <|-- MouseScrollEvent
Event <|-- MouseEvent
@enduml
