@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
abstract class MouseEvent {
    + MousePosition : System.Windows.Point <<get>> <<set>>
}
abstract class Event
!endsub
Event <|-- MouseEvent
@enduml
