@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class MouseClickEvent {
    + HWnd: IntPtr
}
MouseEvent <|-- MouseClickEvent
Event <|-- MouseEvent
MouseClickEvent --> "Button" MouseButton
MouseClickEvent --> "State" MouseButtonState
@enduml
