@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class MouseMoveEvent {
}
abstract class Event
abstract class MouseEvent {
    + MousePosition : Point <<get>> <<set>>
}
MouseEvent <|-- MouseMoveEvent
Event <|-- MouseEvent
@enduml
