@startuml
class ApplicationViewModel {
    + ApplicationViewModel()
    + IsRecording : bool <<get>> <<set>>
}
DependencyObject <|-- ApplicationViewModel
ApplicationViewModel --> "OpenRecordingsDirectoryCommand" ICommand
ApplicationViewModel --> "ExitCommand" ICommand
ApplicationViewModel --> "ToggleRecordingCommand" ICommand
ApplicationViewModel o-> "IsRecordingProperty" DependencyProperty
@enduml
