@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class KeyboardInteractEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<KeyboardInteractEvent>
    # <<override>> Enqueue(KeyboardInteractEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<KeyboardInteractEvent>" <|-- KeyboardInteractEventProducer
@enduml


