@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class Bootstrapper {
    + <<create> Bootstrapper()
    + ComposeImports(object:object) : void
}
!endsub
!include IBootstrapper.puml
IBootstrapper <|-- Bootstrapper
@enduml
