@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class Bootstrapper {
    + ComposeImports(@object:object) : void
}

interface IBootstrapper {
    + ComposeImports(@object:object) : void
}

IBootstrapper <|-- Bootstrapper
@enduml
