@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class ConfigurationManager {
    + LoadConfiguration(path:string) : void
}
class "IEnumerable<T>" {
}
ConfigurationManager --> "Configurations<IConfiguration>" "IEnumerable<T>"
@enduml
