@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

IConfiguration <|-- GlobalModuleConfiguration

class GlobalModuleConfiguration {
    + EnabledModules : IEnumerable<Type> <<get>> <<set>>
    + Parse(string configuration) : void
}

@enduml
