@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

interface IConfigurationManager {
    + LoadConfiguration(path:string) : void
    + Configurations : IEnumerable<IConfiguration> <<get>>
}

@enduml
