@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class ModuleManager {
    + InitializeModules() : void
}
class "IEnumerable<T>" {
}
ModuleManager --> "Modules<IModule>" "IEnumerable<T>"
ModuleManager --> "CollectingModules<ICollectingModule>" "IEnumerable<T>"
@enduml
