@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class RecordingManager {
    - encoder : IEncoder
    - decoder : IDecoder
    - videoCapture : IVideoCapture
    - metadataCapture : IMetadataCapture
    - metadataDeserializer : IMetadataDeserializer
    + IsRecording : bool <<get>> <<private set>>
    + StartRecording() : void
    + StopRecording() : void
    + StartDecoding() : void
    + StopDecoding() : void
}

interface IRecordingManager {
    + IsRecording : bool <<get>>
    + StartRecording() : void
    + StopRecording() : void
    + StartDecoding() : void
    + StopDecoding() : void
}

IRecordingManager <|-- RecordingManager

@enduml
