@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class ClipboardModule {
}
interface IModule {
    + Identifier : Guid
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}
IModule <|-- ICollectingModule
ICollectingModule <|-- ClipboardModule
ClipboardModule --> "  ClipboardCutEventProducer" ClipboardCutEventProducer
ClipboardModule --> "ClipboardCopyEventProducer" ClipboardCopyEventProducer
ClipboardModule --> "   ClipboardPasteEventProducer" ClipboardPasteEventProducer
@enduml