//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MORR.Core.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources_other {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources_other() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MORR.Core.UI.Properties.Resources_other", typeof(Resources_other).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme abbrechen.
        /// </summary>
        public static string Information_Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Information_Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Akkzeptieren.
        /// </summary>
        public static string Information_Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Information_Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Die MORR-Applikation zeichnet Bildschirm-, Tastatur-, Maus-, Zwischenablagen- und Browserdaten auf.
        ///Die gespeicherten Daten können persönlich identifizierbar sein.
        ///Verzichten Sie auf das Eingeben persönlicher Informationen..
        /// </summary>
        public static string Information_Dialog_Content {
            get {
                return ResourceManager.GetString("Information_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme löschen.
        /// </summary>
        public static string Save_Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Save_Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme speichern.
        /// </summary>
        public static string Save_Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Save_Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soll die Aufnahme gespeichert werden?.
        /// </summary>
        public static string Save_Dialog_Content {
            get {
                return ResourceManager.GetString("Save_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schließen.
        /// </summary>
        public static string TrayIcon_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahmeverzeichnis öffnen.
        /// </summary>
        public static string TrayIcon_ContextMenu_OpenRecordingsDirectory {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_OpenRecordingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme starten.
        /// </summary>
        public static string TrayIcon_ContextMenu_StartRecording {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Aufnahme stoppen.
        /// </summary>
        public static string TrayIcon_ContextMenu_StopRecording {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_StopRecording", resourceCulture);
            }
        }
    }
}
