//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MORR.Core.UI.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MORR.Core.UI.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Keep recording.
        /// </summary>
        public static string Confirmation_Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Confirmation_Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete anyway.
        /// </summary>
        public static string Confirmation_Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Confirmation_Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleting a recording cannot be undone.
        ///Do you wish to delete the recording?.
        /// </summary>
        public static string Confirmation_Dialog_Content {
            get {
                return ResourceManager.GetString("Confirmation_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration could not be loaded correctly.
        ///Please check the configuration file or contact an administrator..
        /// </summary>
        public static string Error_Configuration_Invalid {
            get {
                return ResourceManager.GetString("Error_Configuration_Invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No configuration has been specified. Please specify a configuration file as the command line argument or ensure a configuration file named &quot;config.morr&quot; exists relative to the executable..
        /// </summary>
        public static string Error_No_Configuration_Specified {
            get {
                return ResourceManager.GetString("Error_No_Configuration_Specified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The recordings folder could not be found.
        ///Please contact an administrator..
        /// </summary>
        public static string Error_No_Recordings_Directory {
            get {
                return ResourceManager.GetString("Error_No_Recordings_Directory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel recording.
        /// </summary>
        public static string Information_Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Information_Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to I understand.
        /// </summary>
        public static string Information_Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Information_Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The MORR application records screen, keyboard, mouse, clipboard and browser data.
        ///The stored data may be personally identifiable.
        ///Remember not to enter any personal information..
        /// </summary>
        public static string Information_Dialog_Content {
            get {
                return ResourceManager.GetString("Information_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete recording.
        /// </summary>
        public static string Save_Dialog_Button_Cancel {
            get {
                return ResourceManager.GetString("Save_Dialog_Button_Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save recording.
        /// </summary>
        public static string Save_Dialog_Button_OK {
            get {
                return ResourceManager.GetString("Save_Dialog_Button_OK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you wish to save the recording?.
        /// </summary>
        public static string Save_Dialog_Content {
            get {
                return ResourceManager.GetString("Save_Dialog_Content", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string TrayIcon_ContextMenu_Exit {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_Exit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open recordings directory.
        /// </summary>
        public static string TrayIcon_ContextMenu_OpenRecordingsDirectory {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_OpenRecordingsDirectory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Start recording.
        /// </summary>
        public static string TrayIcon_ContextMenu_StartRecording {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_StartRecording", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stop recording.
        /// </summary>
        public static string TrayIcon_ContextMenu_StopRecording {
            get {
                return ResourceManager.GetString("TrayIcon_ContextMenu_StopRecording", resourceCulture);
            }
        }
    }
}
