@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
!startsub default
class ButtonClickEventProducer {
    + <<override>> Notify(eventJson:System.Text.Json.JsonElement) : void
}
abstract class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
!endsub
"WebBrowserEventProducer<T>" "<ButtonClickEvent>" <|-- ButtonClickEventProducer
ButtonClickEventProducer --> "HandledEventLabel" EventLabel
@enduml
