@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
!startsub default
class CloseTabEventProducer {
    + <<override>> Notify(eventJson:System.Text.Json.JsonElement) : void
}
abstract class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
!endsub
"WebBrowserEventProducer<T>" "<CloseTabEvent>" <|-- CloseTabEventProducer
CloseTabEventProducer --> "HandledEventLabel" EventLabel
@enduml
