@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class FileDownloadEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
"WebBrowserEventProducer<T>" "    <FileDownloadEvent>" <|-- FileDownloadEventProducer
FileDownloadEventProducer --> "HandledEventLabel" EventLabel
@enduml
