@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class NavigationEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
"WebBrowserEventProducer<T>" "<NavigationEvent>" <|-- NavigationEventProducer
NavigationEventProducer --> "HandledEventLabel" EventLabel
@enduml
