@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
!startsub default
class TextInputEventProducer {
    + <<override>> Notify(eventJson:System.Text.Json.JsonElement) : void
}
abstract class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
!endsub
"WebBrowserEventProducer<T>" "<TextInputEvent>" <|-- TextInputEventProducer
TextInputEventProducer --> "HandledEventLabel" EventLabel
@enduml
