@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
class ChannelConsumingException {
}
class "Exception"
"Exception" <|-- "ChannelConsumingException"
!endsub
@enduml