@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
class ChannelConsumingException {
    + <<create>> ChannelConsumingException()
    + <<create>> ChannelConsumingException(message : string)
    + <<create>> ChannelConsumingException(message : string, innerException : Exception)
}
!endsub
@enduml