@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
abstract class Event {
    + Timestamp : DateTime <<get>>
    + IssuingModule : Guid <<get>>
}
!endsub
@enduml
