@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

abstract class Event {
    + Timestamp : DateTime
    + IssuingModule : Guid
    + Serialize() : string
    + Deserialize(string serialized) : void
}
@enduml
