@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "SingleConsumerChannelStrategy<T: Event>" {
    # StartReceiving() : void
    + GetEvents(token: CancellationToken) : IAsyncEnumerable<T: Event>
    + Enqueue(event: T) : void
    # {abstract} CreateChannel() : Channel<T: Event>
}
!endsub
@enduml