@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class MouseClickEvent {
    + HWnd : string <<get>> <<set>>
    + MouseAction : MouseAction <<get>> <<set>>
}
MouseEvent <|-- MouseClickEvent
@enduml
