@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class RawConfiguration {
    + RawValue: string <<get>>
    + <<create>>RawConfiguration(rawValue: string)
}
!endsub
@enduml