@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class ConfigurationManager {
    + LoadConfiguration(path:FilePath) : void
}
!endsub
!include IConfigurationManager.puml
ConfigurationManager .UP.|> IConfigurationManager : implements
@enduml
