@startuml
class Bootstrapper {
    + Bootstrapper()
    + ComposeImports(@object:object) : void
}
class ModuleLoadContext {
    + ModuleLoadContext(pluginPath:string)
}
IBootstrapper <|-- Bootstrapper
Bootstrapper +-- ModuleLoadContext
AssemblyLoadContext <|-- ModuleLoadContext
@enduml
