@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class WindowManagementModule {
}


interface IModule {
    + Identifier : Guid
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}

IModule <|-- WindowManagementModule
WindowManagementModule --> "WindowFocusEventProducer" WindowFocusEventProducer
WindowManagementModule ---> "WindowMovementEventProducer" WindowMovementEventProducer
WindowManagementModule --> "       WindowResizingEventProducer" WindowResizingEventProducer
WindowManagementModule ---> "WindowStateChangedEventProducer" WindowStateChangedEventProducer
@enduml
