@startuml
class InteractiveCommandLine {
    + InteractiveCommandLine(consoleFormatter:IConsoleFormatter)
    + Launch(completionAction:Action) : void
}
IInteractiveCommandLine <|-- InteractiveCommandLine
@enduml
