@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class NativeMethods {
    + {static} DoWin32MessageLoop()
    + {static} StopMessageLoop()
    + {static} IsKeyPressed(VirtualKeyCode virtualKeyCode)
    + {static} TrySetKeyboardHook(callback: LowLevelKeyboardProc, handle: IntPtr)
    + {static} GetClipboardText()
    + {static} GetAssociatedWindow()
}
!endsub
@enduml