@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ButtonClickEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
"WebBrowserEventProducer<T>" "<ButtonClickEvent>" <|-- ButtonClickEventProducer
ButtonClickEventProducer --> "HandledEventLabel" EventLabel
@enduml
