@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class CloseTabEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<CloseTabEvent>
    # <<override>> Enqueue(CloseTabEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<CloseTabEvent>" <|-- CloseTabEventProducer
@enduml
