@startuml
class CloseTabEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer`1"<T> {
}
"WebBrowserEventProducer`1" "<CloseTabEvent>" <|-- CloseTabEventProducer
CloseTabEventProducer --> "HandledEventLabel" EventLabel
@enduml
