@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class FileDownloadEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<FileDownloadEvent>
    # <<override>> Enqueue(FileDownloadEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<FileDownloadEvent>" <|-- FileDownloadEventProducer
@enduml
