@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class HoverEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<HoverEvent>
    # <<override>> Enqueue(HoverEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<HoverEvent>" <|-- HoverEventProducer
@enduml
