@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class HoverEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
"WebBrowserEventProducer<T>" "<HoverEvent>" <|-- HoverEventProducer
HoverEventProducer --> "HandledEventLabel" EventLabel
@enduml
