@startuml
class HoverEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer`1"<T> {
}
"WebBrowserEventProducer`1" "<HoverEvent>" <|-- HoverEventProducer
HoverEventProducer --> "HandledEventLabel" EventLabel
@enduml
