@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class NavigationEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<NavigationEvent>
    # <<override>> Enqueue(NavigationEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<NavigationEvent>" <|-- NavigationEventProducer
@enduml
