@startuml
class NavigationEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer`1"<T> {
}
"WebBrowserEventProducer`1" "<NavigationEvent>" <|-- NavigationEventProducer
NavigationEventProducer --> "HandledEventLabel" EventLabel
@enduml
