@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class OpenTabEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<OpenTabEvent>
    # <<override>> Enqueue(OpenTabEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<OpenTabEvent>" <|-- OpenTabEventProducer
@enduml
