@startuml
class OpenTabEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer`1"<T> {
}
"WebBrowserEventProducer`1" "<OpenTabEvent>" <|-- OpenTabEventProducer
OpenTabEventProducer --> "HandledEventLabel" EventLabel
@enduml
