@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class SwitchTabEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<SwitchTabEvent>
    # <<override>> Enqueue(SwitchTabEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<SwitchTabEvent>" <|-- SwitchTabEventProducer
@enduml
