@startuml
class SwitchTabEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer`1"<T> {
}
"WebBrowserEventProducer`1" "<SwitchTabEvent>" <|-- SwitchTabEventProducer
SwitchTabEventProducer --> "HandledEventLabel" EventLabel
@enduml
