@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class TextSelectionEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<TextSelectionEvent>
    # <<override>> Enqueue(TextSelectionEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<TextSelectionEvent>" <|-- TextSelectionEventProducer
@enduml
