@startuml
class TextInputEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer`1"<T> {
}
"WebBrowserEventProducer`1" "<TextInputEvent>" <|-- TextInputEventProducer
TextInputEventProducer --> "HandledEventLabel" EventLabel
@enduml
