@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class TextInputEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<TextInputEvent>
    # <<override>> Enqueue(TextInputEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<TextInputEvent>" <|-- TextInputEventProducer
@enduml
