@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class TextInputEventProducer {
    + <<override>> Notify(eventJson:JsonElement) : void
}
class "WebBrowserEventProducer<T>" {
}
enum "EventLabel"
"WebBrowserEventProducer<T>" "<TextInputEvent>" <|-- TextInputEventProducer
TextInputEventProducer --> "HandledEventLabel" EventLabel
@enduml
