@startuml MORR
skinparam monochrome true
skinparam linetype ortho
skinparam classAttributeIconSize 0
!pragma useNewPackage

left to right direction
hide empty fields

package MORR {
    !startsub SHARED
    package SHARED #E6E6E6 {
        package Configuration <<Rectangle>> #BFBFBF {
            !includesub application/Common/Shared/Configuration/IConfiguration.puml!default

            !includesub application/Core/MORR/Configuration/InvalidConfigurationException.puml!default

            !includesub application/Common/Shared/Configuration/RawConfiguration.puml!default

            IConfiguration ..> RawConfiguration : "uses"
        }

        together {
            !includesub application/Common/Shared/Modules/IModule.puml!default
        }

        together {
            !includesub application/Common/Shared/Events/Event.puml!default

            package Queue <<Rectangle>> #BFBFBF {

                !includesub application/Common/Shared/Events/Queue/IDecodableEventQueue.puml!default

                !includesub application/Common/Shared/Events/Queue/IEncodableEventQueue.puml!default

                !includesub application/Common/Shared/Events/Queue/IReadOnlyEventQueue.puml!default

                !includesub application/Common/Shared/Events/Queue/ISupportDeserializationEventQueue.puml!default

                abstract class "DecodableEventQueue<T: Event>" {
                    # <<create>> DecodableEventQueue(storageStrategy: IEventQueueStorageStrategy<T: Event>)
                    + GetEvents(cancellationToken: CancellationToken) : IAsyncEnumerable<T: Event>
                    + Enqueue(event: T) : void
                }

                abstract class "EncodableEventQueue<T: Event>" {
                    # <<create>> EncodableEventQueue(storageStrategy: IEventQueueStorageStrategy<T: Event>)
                    + GetEvents(cancellationToken: CancellationToken) : IAsyncEnumerable<T: Event>
                    + Enqueue(event: T) : void
                }

                abstract class "ReadOnlyEventQueue<T: Event>" {
                    # <<create>> ReadOnlyEventQueue(storageStrategy: IEventQueueStorageStrategy<T: Event>)
                    + GetEvents(cancellationToken: CancellationToken) : IAsyncEnumerable<T: Event>
                    + Enqueue(event: T) : void
                }

                !includesub application/Common/Shared/Events/Queue/SupportDeserializationEventQueue.puml!default
                !includesub application/Common/Shared/Events/Queue/Aliases.puml!default

                package StorageStrategy <<Rectangle>> #E6E6E6 {
                    !includesub application/Common/Shared/Events/Queue/Strategy/ChannelConsumingException.puml!default

                    !includesub application/Common/Shared/Events/Queue/Strategy/IEventQueueStorageStrategy.puml!default

                    together {
                        !includesub application/Common/Shared/Events/Queue/Strategy/MultiConsumer/MultiConsumerChannelStrategy.puml!default
                        !includesub application/Common/Shared/Events/Queue/Strategy/MultiConsumer/BoundedMultiConsumerChannelStrategy.puml!default
                        !includesub application/Common/Shared/Events/Queue/Strategy/MultiConsumer/UnboundedMultiConsumerChannelStrategy.puml!default

                        "IEventQueueStorageStrategies<T: Event>" <|.. "MultiConsumerChannelStrategy<T: Event>"
                        "MultiConsumerChannelStrategy<T: Event>" <|-- "BoundedMultiConsumerChannelStrategy<T: Event>"
                        "MultiConsumerChannelStrategy<T: Event>" <|-- "UnboundedMultiConsumerChannelStrategy<T: Event>"
                        "BoundedMultiConsumerChannelStrategy<T: Event>" ..> ChannelConsumingException: "throws"
                    }
                    
                    together {
                        !includesub application/Common/Shared/Events/Queue/Strategy/SingleConsumer/SingleConsumerChannelStrategy.puml!default

                        !includesub application/Common/Shared/Events/Queue/Strategy/SingleConsumer/BoundedSingleConsumerChannelStrategy.puml!default
                        !includesub application/Common/Shared/Events/Queue/Strategy/SingleConsumer/UnboundedSingleConsumerChannelStrategy.puml!default

                        "IEventQueueStorageStrategies<T: Event>" <|.. "SingleConsumerChannelStrategy<T: Event>"
                        "SingleConsumerChannelStrategy<T: Event>" <|-- "BoundedSingleConsumerChannelStrategy<T: Event>"
                        "SingleConsumerChannelStrategy<T: Event>" <|-- "UnboundedSingleConsumerChannelStrategy<T: Event>"
                        "BoundedSingleConsumerChannelStrategy<T: Event>" ..> ChannelConsumingException : "throws"
                    }
                }

                "IEventQueueStorageStrategy<T: Event>" "1" *-- "ReadOnlyEventQueue<T: Event>"
                "IEventQueueStorageStrategy<T: Event>" "1" *-- "EncodableEventQueue<T: Event>"
                "IEventQueueStorageStrategy<T: Event>" "1" *-- "DecodableEventQueue<T: Event>"

                "BoundedMultiConsumerChannelStrategy<T: Event>" <.. "DefaultEventQueue<T: Event>" : "uses"
                "BoundedMultiConsumerChannelStrategy<T: Event>" <.. "NonDeserializableEventQueue<T: Event>" : "uses"
                "BoundedMultiConsumerChannelStrategy<T: Event>" <.. "DefaultDecodableEventQueue<T: Event>" : "uses"
                "BoundedSingleConsumerChannelStrategy<T: Event>" <.. "DefaultEncodableEventQueue<T: Event>" : "uses"

                ' EventQueue
                "IDecodableEventQueue<T: Event>" <|.. "DecodableEventQueue<T: Event>"
                "IEncodableEventQueue<T: Event>" <|.. "EncodableEventQueue<T: Event>"
                "IReadOnlyEventQueue<T: Event>" <|.. "ReadOnlyEventQueue<T: Event>"
                "ISupportDeserializationEventQueue<T: Event>" <|.. "SupportDeserializationEventQueue<T: Event>"
                "ReadOnlyEventQueue<T: Event>" <|-- "SupportDeserializationEventQueue<T: Event>"
                "SupportDeserializationEventQueue<T: Event>" <|-- "DefaultEventQueue<T: Event>"
                "EncodableEventQueue<T: Event>" <|-- "DefaultEncodableEventQueue<T: Event>"
                "DecodableEventQueue<T: Event>" <|-- "DefaultDecodableEventQueue<T: Event>"
                "ReadOnlyEventQueue<T: Event>" <|-- "NonDeserializableEventQueue<T: Event>"
            }
        }

        package Utility <<Rectangle>> #BFBFBF {
            !includesub application/Common/Shared/Utility/DirectoryPath.puml!default

            !includesub application/Common/Shared/Utility/FilePath.puml!default

            !includesub application/Common/Shared/Utility/GlobalHook.puml!default

            !includesub application/Common/Shared/Utility/NativeMethods.puml!default

            !includesub application/Common/Shared/Utility/Utility.puml!default

            together {
                !includesub application/Common/Shared/Utility/Exceptions/HookLibraryException.puml!default
            }

            GlobalHook ..> HookLibraryException : "throws"
            GlobalHook ..> NativeMethods : "uses"
        }
    }
    !endsub 

    !startsub CORE
    package "CORE" #E6E6E6 {
        !includesub application/Core/MORR/IBootstrapper.puml!default

        !includesub application/Core/MORR/Bootstrapper.puml!default

        !includesub application/Core/MORR/BootstrapperConventions.puml!default

        package ConfigurationManagement <<Rectangle>> #BFBFBF {
            !includesub application/Core/MORR/Configuration/IConfigurationManager.puml!default

            !includesub application/Core/MORR/Configuration/ConfigurationManager.puml!default

            !includesub application/Core/MORR/Configuration/InvalidConfigurationException.puml!default

            IConfigurationManager <|.. ConfigurationManager
            ConfigurationManager ..> InvalidConfigurationException : "throws"
        }

        package Session <<Rectangle>> #BFBFBF {
            interface ISessionManager {
                + IsRecording : bool <<get>>
                + StartRecording() : void
                + StopRecording() : void
                + Process(files: IEnumerable<FilePath>) : void
            }

            class SessionManager {
                - videoCapture : IVideoCapture
                + IsRecording : bool <<get>> <<private set>>
                + StartRecording() : void
                + StopRecording() : void
                + Process(files: IEnumerable<FilePath>) : void
            }

            together {
                abstract class RecordingException {

                }

                class AlreadyRecordingException {

                }

                class NotRecordingException {

                }

                RecordingException <|-- AlreadyRecordingException
                RecordingException <|-- NotRecordingException
            }

            ISessionManager <|-- SessionManager
            SessionManager ..> AlreadyRecordingException : "throws"
            SessionManager ..> NotRecordingException : "throws
        }

        package Modules <<Rectangle>> #BFBFBF {
            !includesub application/Core/MORR/Modules/IModuleManager.puml!default

            !includesub application/Core/MORR/Modules/ModuleManager.puml!default

            !includesub application/Core/MORR/Modules/GlobalModuleConfiguration.puml!default

            IModuleManager <|-- ModuleManager
            ModuleManager *-- "1" GlobalModuleConfiguration
        }

        package Data <<Rectangle>> #BFBFBF {
            together {
                !includesub application/Core/MORR/Data/Capture/CaptureException.puml!default

                together {
                    !includesub application/Core/MORR/Data/Capture/Video/DirectXVideoSample.puml!default

                    !includesub application/Core/MORR/Data/Capture/Video/VideoSample.puml!default

                    together {
                        !includesub application/Core/MORR/Data/Capture/Video/Exceptions/VideoCaptureException.puml!default

                        CaptureException <|-- VideoCaptureException
                    }

                    package Desktop <<Rectangle>> #E6E6E6 {
                        !includesub application/Core/MORR/Data/Capture/Video/Desktop/DesktopCapture.puml!default

                        !includesub application/Core/MORR/Data/Capture/Video/Desktop/DesktopCaptureConfiguration.puml!default

                        !includesub application/Core/MORR/Data/Capture/Video/Desktop/VideoSampleProducer.puml!default

                        together {
                            !includesub application/Core/MORR/Data/Capture/Video/Desktop/Utility/Direct3D11Helper.puml!default

                            !includesub application/Core/MORR/Data/Capture/Video/Desktop/Utility/GraphicsCaptureHelper.puml!default

                            class MonitorInfo {
                                + IsPrimary: bool <<get>> <<set>>
                                + ScreenSize: Vector2 <<get>> <<set>>
                                + MonitorArea: Rect <<get>> <<set>>
                                + WorkArea: Rect <<get>> <<set>>
                                + DeviceName: string <<get>> <<set>>
                                + Hmon: IntPtr <<get>> <<set>>
                            }

                            !includesub application/Core/MORR/Data/Capture/Video/Desktop/Utility/MonitorEnumerationHelper.puml!default

                            MonitorEnumerationHelper ..> MonitorInfo : "uses"
                        }

                        DesktopCapture --* "1 VideoSampleProducer" VideoSampleProducer
                        DesktopCapture --* "1 Configuration" DesktopCaptureConfiguration
                        DesktopCapture ..> MonitorEnumerationHelper : "uses"
                        VideoSampleProducer ..> Direct3D11Helper : "uses"
                    }

                    DesktopCapture ..> VideoCaptureException: "throws"
                    DirectXVideoSample --|> VideoSample
                }
            }

            together {
                !includesub application/Core/MORR/Data/IntermediateFormat/IntermediateFormatSample.puml!default

                together {
                    !includesub application/Core/MORR/Data/IntermediateFormat/Json/JsonIntermediateFormatDeserializer.puml!default

                    !includesub application/Core/MORR/Data/IntermediateFormat/Json/JsonIntermediateFormatSample.puml!default

                    !includesub application/Core/MORR/Data/IntermediateFormat/Json/JsonIntermediateFormatSerializer.puml!default
                }

                IntermediateFormatSample <|-- JsonIntermediateFormatSample
            }

            package Transcoding <<Rectangle>> #E6E6E6 {
                !includesub application/Core/MORR/Data/Transcoding/IDecoder.puml!default

                !includesub application/Core/MORR/Data/Transcoding/IEncoder.puml!default

                package MPEG <<Rectangle>> #BFBFBF {
                    !includesub application/Core/MORR/Data/Transcoding/MPEG/MPEGEncoder.puml!default
                    
                    !includesub application/Core/MORR/Data/Transcoding/MPEG/MPEGEncoderConfiguration.puml!default
                }

                package Json <<Rectangle>> #BFBFBF {
                    !includesub application/Core/MORR/Data/Transcoding/Json/JsonDecoder.puml!default

                    !includesub application/Core/MORR/Data/Transcoding/Json/JsonEncoder.puml!default
                }

                IEncoder <|.. MpegEncoder
                IDecoder <|.. JsonDecoder
                IEncoder <|-- JsonEncoder
                MpegEncoder --* "1 Configuration" MpegEncoderConfiguration
                MpegEncoder --* "1 VideoQueue" "IEncodableEventQueue<T: Event>"
            }
        }

        SessionManager --* "1" IEncoder
        SessionManager --* "0..1" IDecoder
        SessionManager --* "1" IModuleManager
        SessionManager ..> IBootstrapper : "uses"
        Bootstrapper ..> BootstrapperConventions : "uses"
        IBootstrapper <|.. Bootstrapper
    }
    !endsub

    VideoSample --|> Event
    DesktopCapture ..|> IModule
    DesktopCaptureConfiguration ..|> IConfiguration

    GlobalModuleConfiguration ..|> IConfiguration
    GlobalModuleConfiguration --* "* EnabledModules" IModule
    ModuleManager --* "* Modules" IModule

    IConfigurationManager --* "*" IConfiguration

    IntermediateFormatSample --|> Event
    JsonIntermediateFormatDeserializer ..|> IModule
    JsonIntermediateFormatDeserializer --* "* EventQueues" "ISupportDeserializationEventQueue<T: Event>"
    JsonIntermediateFormatDeserializer --* "1 IntermediateFormatSampleQueue" "IDecodableEventQueue<T: Event>"
    JsonIntermediateFormatSerializer ..|> IModule
    JsonIntermediateFormatSerializer --|> "DefaultEncodableEventQueue<T: Event>"
    JsonIntermediateFormatSerializer --* "* EventQueues" "IReadOnlyEventQueue<T: Event>"

    MpegEncoderConfiguration ..|> IConfiguration
    JsonDecoder --|> "DefaultDecodableEventQueue<T: Event>"
    JsonEncoder --* "1 IntermediateFormatSampleQueue" "IEncodableEventQueue<T: Event>"

    !startsub UI
    package "UI" #E6E6E6 {
        class ErrorDialog <<partial>> {
            + ErrorDialog(errorMessage:string)
            + ErrorMessage : string <<get>>
        }

        class InformationDialog <<partial>> {
            + InformationDialog()
        }

        class SaveDialog <<partial>> {
            + SaveDialog()
        }

        class ApplicationViewModel {
            + ApplicationViewModel()
            + IsRecording : bool <<get>> <<set>>
        }
        
        class NotifyIcon {
            + NotifyIcon()
            + Tooltip : string <<get>> <<set>>
            + CommandParameter : object <<get>> <<set>>
        }
        
        class RelayCommand {
            + RelayCommand(execute:Action<object>, canExecute:Predicate<object>?)
            + CanExecute(parameter:object) : bool
            + Execute(parameter:object) : void
        }

        interface ICommand {

        }

        class ContextMenu {

        }

        class ImageSource {

        }

        class App <<partial>> {

        }        
    }

    ' UI
    ApplicationViewModel --> "1" IRecordingManager : uses
    ApplicationViewModel o--> "n" ICommand
    App --> "1" ApplicationViewModel
    ApplicationViewModel o-> SaveDialog
    ApplicationViewModel o-> ErrorDialog
    ApplicationViewModel o-> InformationDialog
    App o-> NotifyIcon
    NotifyIcon --> "IconSource" ImageSource
    NotifyIcon --> "Command" ICommand
    NotifyIcon --> "ContextMenu" ContextMenu
    ICommand <|.. RelayCommand
    !endsub

    !startsub CLI
    package "CLI" #E6E6E6 {
        class Program {
            + {static} Main(args:string[]) : int
        }

        together {
            interface "ICommand<T: CommandOptions>" {
                + Execute(options: T) : int
            }

            abstract class CommandOptions {
                + IsVerbose: bool <<get>> <<set>>
            }

            together {
                class ProcessCommand {
                    + Execute(options: ProcessOptions) : int
                }

                class ProcessOptions {
                    + IsVerbose: bool <<get>> <<set>>
                    + ConfigPath: string <<get>> <<set>>
                    + InputFile: string <<get>> <<set>>
                }

                ProcessCommand ..> ProcessOptions : "uses"
            }

            together {
                class RecordCommand {
                    + Execute(options: RecordOptions) : int
                }

                class RecordOptions {
                    + IsVerbose: bool <<get>> <<set>>
                    + ConfigPath: string <<get>> <<set>>
                }

                RecordCommand ..> RecordOptions : "uses"
            }

            together {
                class ValidateCommand {
                    + Execute(options: ValidateOptions) : int
                }

                class ValidateOptions {
                    + IsVerbose: bool <<get>> <<set>>
                    + ConfigPath: string <<get>> <<set>>
                }

                ValidateCommand ..> ValidateOptions : "uses"
            }

            RecordCommand ..|> "ICommand<T: CommandOptions>"
            ValidateCommand ..|> "ICommand<T: CommandOptions>"
            ProcessCommand ..|> "ICommand<T: CommandOptions>"

            RecordOptions --|> CommandOptions
            ValidateOptions --|> CommandOptions
            ProcessOptions --|> CommandOptions
        }

        together {
            class InteractiveCommandLine {
                + Launch(cancelAction: Action) : void
            }
        }

        together {
            class IOutputFormatter {

            }

            class OutputFormatter {
                ~ IsVerbose: bool <<get>> <<set>>
                + Encode(path: DirectoryPath) : void
                ~ {static} PrintError(exception: Exception) : void
                ~ {static} PrintDebug(message: string) : void
            }

            OutputFormatter ..|> IOutputFormatter
        }

        ProcessCommand ..> OutputFormatter : "uses"
        ValidateCommand ..> OutputFormatter : "uses"
        RecordCommand ..> OutputFormatter : "uses"
        RecordCommand ..> InteractiveCommandLine :"uses"

        Program ..> "ICommand<T: CommandOptions>": "uses"
        Program ..> CommandOptions : "uses"
    }
    !endsub

    ProcessCommand ..> ISessionManager : "uses"
    RecordCommand ..> ISessionManager : "uses"
    RecordCommand ..> NativeMethods : "uses"
    ValidateCommand ..> IBootstrapper : "uses"
    ValidateCommand ..> IModuleManager : "uses"
    IOutputFormatter --|> IEncoder
    OutputFormatter --* "1 MetadataQueue" "IEncodableEventQueue<T: Event>"

    package "MODULES" #E6E6E6 {
        !startsub MODULES_CLIPBOARD
        package "CLIPBOARD" #BFBFBF {
            class ClipboardModule {
            
            }

            abstract class ClipboardEvent {
            
            }

            class ClipBoardInteractEvent {
                + Text : string <<get>> <<set>>
            }

            enum InteractionType {
                CLEAR
                COPY
                CUT
                PASTE
            }
        }

        'Clipboard
        IModule <|.. ClipboardModule
        Event <|-- ClipboardEvent
        ClipboardEvent <|-- ClipBoardInteractEvent
        ClipBoardInteractEvent --> "Interaction" InteractionType
        ClipBoardInteractEvent +-- InteractionType
        !endsub

        !startsub MODULES_KEYBOARD
        package "KEYBOARD" #BFBFBF {
            class KeyboardModule {
            
            }

            abstract class KeyboardEvent {
            }
            
            class KeyBoardInteractEvent {
                + PressedKey: Key
            }
        }

        ' Keyboard
        Event <|-- KeyboardEvent
        IModule <|.. KeyboardModule
        KeyboardEvent <|-- KeyBoardInteractEvent
        !endsub

        !startsub MODULES_MOUSE
        package "MOUSE" #BFBFBF {
            class MouseModule {
        
            }

            
            abstract class MouseEvent {
            }

            class MouseMoveEvent {
                + Movement: Vector2
            }

            enum MouseButton {
                LEFT,
                CENTER,
                RIGHT
            }

            enum MouseButtonState {

            }
            
            class MouseClickEvent {
                + HWnd: IntPtr
            }
            
            class MouseScrollEvent {
                + HWnd: IntPtr
                + ScrollAmount : short <<get>> <<set>>
            }
        }

        ' Mouse
        Event <|-- MouseEvent
        IModule <|.. MouseModule
        MouseEvent <|-- MouseClickEvent
        MouseEvent <|-- MouseScrollEvent
        MouseEvent <|-- MouseMoveEvent
        MouseClickEvent --> "Button" MouseButton
        MouseClickEvent --> "State" MouseButtonState
        !endsub

        !startsub MODULES_WEBBROWSER
        package "WEBBROWSER" #BFBFBF {
            class WebBrowserModule {
        
            }

            class ButtonClickEvent {
                + Button : string <<get>> <<set>>
                + URL: Uri
            }
            
            class CloseTabEvent {
            }
            
            class FileDownloadEvent {
                + MIMEType : string <<get>> <<set>>
                + FileURL: Uri
            }
            
            class HoverEvent {
                + HoveredElement : string <<get>> <<set>>
            }
            class NavigationEvent {
            }
            
            class OpenTabEvent {
            }
            
            class SwitchTabEvent {
                + NewTabID: Guid
            }
            
            class TextInputEvent {
                + InputtedText : string <<get>> <<set>>
                + Textbox : string <<get>> <<set>>
            }
            
            class TextSelectionEvent {
                + SelectedText : string <<get>> <<set>>
            }
            
            abstract class WebBrowserEvent {
                + TabID: Guid
                + CurrentURL: Uri
            }
        }

        ' WebBrowser
        Event <|-- WebBrowserEvent
        IModule <|.. WebBrowserModule
        WebBrowserEvent <|-- ButtonClickEvent
        WebBrowserEvent <|-- CloseTabEvent
        WebBrowserEvent <|-- FileDownloadEvent
        WebBrowserEvent <|-- HoverEvent
        WebBrowserEvent <|-- NavigationEvent
        WebBrowserEvent <|-- OpenTabEvent
        WebBrowserEvent <|-- SwitchTabEvent
        WebBrowserEvent <|-- TextInputEvent
        WebBrowserEvent <|-- TextSelectionEvent
        !endsub

        !startsub MODULES_WINDOWMANAGEMENT
        package "WINDOWMANAGEMENT" #BFBFBF {
            class WindowManagementModule {
        
            }

            abstract class WindowEvent {
                + Title : string <<get>> <<set>>
                + ProcessName : string <<get>> <<set>>
            }
            
            class WindowFocusEvent {

            }

            class WindowMovementEvent {
                + OldLocation: Vector2
                + NewLocation: Vector2
            }

            class WindowResizingEvent {
                + OldSize: Size
                + NewSize: Size
            }

            class WindowStateChangedEvent {
                + State: WindowState
            }
        }

        ' WindowManagement
        Event <|-- WindowEvent
        IModule <|.. WindowManagementModule
        WindowEvent <|-- WindowFocusEvent
        WindowEvent <|-- WindowMovementEvent
        WindowEvent <|-- WindowResizingEvent
        WindowEvent <|-- WindowStateChangedEvent
        !endsub
    }
}
@enduml
