@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
abstract class WindowEvent {
    + Title : string <<get>> <<set>>
    + ProcessName : string <<get>> <<set>>
}
Event <|-- WindowEvent
@enduml
