@startuml
class WindowMessageSink {
    + WindowMessageSink()
    +  <<event>> WindowMessage : WindowMessageEventHandler? 
    +  <<event>> TaskbarCreated : TaskbarCreatedEventHandler? 
    + Dispose() : void
}
IDisposable <|-- WindowMessageSink
WindowMessageSink --> "WindowHandle" IntPtr
@enduml
