@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class ClipboardModule {
}
interface ICollectingModule
ICollectingModule <|-- ClipboardModule

interface IModule {
    + Identifier : Guid
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}

IModule <|-- ICollectingModule
ClipboardModule --> "  ClipboardCutEventProducer" ClipboardCutEventProducer
ClipboardModule --> "ClipboardCopyEventProducer" ClipboardCopyEventProducer
ClipboardModule --> "   ClipboardPasteEventProducer" ClipboardPasteEventProducer
@enduml
