@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class KeyBoardInteractEvent {
}
KeyboardEvent <|-- KeyBoardInteractEvent
Event <|-- KeyboardEvent
KeyBoardInteractEvent --> "PressedKey" Key
@enduml
