@startuml
class Utility <<static>> {
    + {static} SetAndDispatch(variable:bool, value:bool, onTrue:Action, onFalse:Action) : void
    + {static} GetTypeFromAnyAssembly(type:string) : Type?
    + {static} GetWindowTitleFromHwnd(hwnd:IntPtr) : string
    + {static} GetProcessNameFromHwnd(hwnd:IntPtr) : string
    + {static} IsRectSizeEqual(rectA:Rectangle, rectB:Rectangle) : bool
    + {static} GetWindowWidth(rect:Rectangle) : int
    + {static} GetWindowHeight(rect:Rectangle) : int
}
@enduml
