@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ClipboardCopyEvent {
}
abstract class ClipboardEvent
abstract class Event
ClipboardEvent <|-- ClipboardCopyEvent
Event <|-- ClipboardEvent
@enduml
