@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ClipboardCutEvent {
}
abstract class ClipboardEvent
abstract class Event
ClipboardEvent <|-- ClipboardCutEvent
Event <|-- ClipboardEvent
@enduml
