@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ClipboardPasteEvent {
}
abstract class Event
abstract class ClipboardEvent {
    + ClipboardText : string <<get>> <<set>>
}
ClipboardEvent <|-- ClipboardPasteEvent
Event <|-- ClipboardEvent
@enduml
