@startuml
'skinparam monochrome true
hide footbox
title Core initialization from UI
actor User
create ":App" as UIApp
User -> UIApp : starts UI application
activate UIApp
create ":NotifyIconControl" as TrayIcon
UIApp -> TrayIcon : <<create>>
UIApp <-- TrayIcon
create ":ApplicationViewModel" as ApplicationViewModel
UIApp -> ApplicationViewModel : <<create>>
activate ApplicationViewModel
create ":SessionManager" as SessionManager
ApplicationViewModel -> SessionManager : <<create>>
activate SessionManager
create ":Bootstrapper" as Bootstrapper
SessionManager -> Bootstrapper : <<create>>
activate Bootstrapper
create ":IEnumerable<IModule>" as IModulesImport
Bootstrapper [#blue]-> IModulesImport : <<create>>
note right
Implicitly created through MEF
end note
create ":IEnumerable<IConfiguration>" as IConfigurationsImport
Bootstrapper [#blue]-> IConfigurationsImport : <<create>>
note right
Implicitly created through MEF
end note
deactivate Bootstrapper
create ":ModuleManager" as ModuleManager
SessionManager -> ModuleManager : <<create>>
SessionManager <-- ModuleManager
create ":ConfigurationManager" as ConfigurationManager
SessionManager -> ConfigurationManager : <<create>>
SessionManager <-- ConfigurationManager

SessionManager -> Bootstrapper : ComposeImports(ModuleManager)
activate Bootstrapper
Bootstrapper -> ModuleManager : <<Import IModules, GlobalModuleConfiguration through MEF>>
deactivate Bootstrapper
SessionManager -> Bootstrapper : ComposeImports(ConfigurationManager)
activate Bootstrapper
Bootstrapper -> ConfigurationManager : <<Import IConfiguration through MEF>>

create ":MPEGEncoder" as MPEGEncoder
Bootstrapper -> MPEGEncoder : <<create through MEF>>
Bootstrapper <-- MPEGEncoder
create ":JsonEncoder" as JsonEncoder
Bootstrapper -> JsonEncoder : <<create through MEF>>
Bootstrapper <-- JsonEncoder
create ":JsonDecoder" as JsonDecoder
Bootstrapper -> JsonDecoder : <<create through MEF>>
Bootstrapper <-- JsonDecoder
create ":DesktopCapture" as DesktopCapture
Bootstrapper -> DesktopCapture : <<create through MEF>>
Bootstrapper <-- DesktopCapture
create ":JsonIntermediateFormatSerializer" as JsonIntermediateFormatSerializer
Bootstrapper -> JsonIntermediateFormatSerializer : <<create through MEF>>
Bootstrapper <-- JsonIntermediateFormatSerializer
create ":JsonIntermediateFormatDeserializer" as JsonIntermediateFormatDeserializer
Bootstrapper -> JsonIntermediateFormatDeserializer : <<create through MEF>>
Bootstrapper <-- JsonIntermediateFormatDeserializer

deactivate Bootstrapper

SessionManager -> ConfigurationManager : LoadConfiguration(path)
activate ConfigurationManager
ConfigurationManager -> IConfigurationsImport : <<foreach>> Parse(section)
SessionManager <-- ConfigurationManager
deactivate ConfigurationManager

SessionManager -> ModuleManager : InitializeModules()
activate ModuleManager
ModuleManager -> IModulesImport : <<foreach>> Initialize()
SessionManager <-- ModuleManager
deactivate ModuleManager

ApplicationViewModel <-- SessionManager
deactivate SessionManager
UIApp <-- ApplicationViewModel
deactivate ApplicationViewModel
deactivate UIApp
@enduml
