@startuml
skinparam linetype ortho
skinparam monochrome true
skinparam classAttributeIconSize 0
class DownloadEventFactory {
	+ createEvent(downloadItem: downloads.DownloadItem) : DownloadEvent
}
DownloadListener *-- DownloadEventFactory
DownloadEventFactory .DOWN.> DownloadEvent : creates
@enduml
