@startuml
skinparam linetype ortho
skinparam monochrome true
skinparam classAttributeIconSize 0
class TabListener {
    + TabListener(callback : function(BrowserEvent) : void)
    + start()
    + stop()
}
interface IListener {
    + IListener(callback : function(BrowserEvent) : void)
    + start() : void
    + stop() : void
}
TabListener .UP.|> IListener : implements
/'class OpenTabEvent {
    + OpenTabEvent(tabID : int, windowID : int, url : string)
}
class CloseTabEvent {
    + CloseTabEvent(tabID : int, windowID : int, url : string)
}
class SwitchTabEvent {
    + newTab : int
    + SwitchTabEvent(tabID : int, windowID : int, newTabID : int, url : string)
}
class NavigationEvent {
    + NavigationEvent(tabID : int, windowID : int, url : string)
} '/
TabListener ..> OpenTabEvent : creates
TabListener ..> CloseTabEvent : creates
TabListener ..> SwitchTabEvent : creates
TabListener ..> NavigationEvent : creates

@enduml
