@startuml
skinparam linetype ortho
skinparam monochrome true
skinparam classAttributeIconSize 0
class TextInputEvent extends BrowserEvent {
    + text : string
    + target : string
    + TextInputEvent(tabID : number, windowID : number, text : string, target : string, url : string)
}
interface IEvent {
    + timeStamp : Date
    + issuingModule : number
    + type : EventType
    + serialize() : string
}

IEvent <|.DOWN. BrowserEvent : implements
class BrowserEvent {
    + BrowserEvent(type : EventType, tabID : number, windowID: number, url : string)
    + timeStamp : Date
    + issuingModule : number
    + type : EventType
    + serialize() : string
    + tabID : number
    + url : URL
    + windowID : number
}
@enduml
