@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ClipboardCutEventProducer {
    + StartCapture() : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
"DefaultEventQueue<T>" "     <ClipboardCutEvent>" <|-- ClipboardCutEventProducer
@enduml
