@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ClipboardCopyEventProducer {
    + StartCapture() : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
"DefaultEventQueue<T>" "     <ClipboardCopyEvent>" <|-- ClipboardCopyEventProducer

@enduml
