@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
!startsub default
class ClipboardCopyEventProducer {
    + StartCapture(windowMessageSink:IClipboardWindowMessageSink, nativeClip:INativeClipboard) : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
!endsub
"DefaultEventQueue<T>" "     <ClipboardCopyEvent>" <|-- ClipboardCopyEventProducer

@enduml
