@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class ClipboardPasteEventProducer {
    + StartCapture() : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
"DefaultEventQueue<T>" "    <ClipboardPasteEvent>" <|-- ClipboardPasteEventProducer
@enduml
