@startuml
skinparam linetype ortho
skinparam monochrome true
skinparam classAttributeIconSize 0
class DOMEventRecorder {
    start() : void
    stop() : void
}
DOMEventRecorder .RIGHT.> DOMEventType : uses
DOMEventRecorder .DOWN.> DOMListener : messages through browser API
enum DOMEventType {
    CLICK
    CHANGE
    DBCLICK
    KEYUP
    KEYDOWN
    INPUT
    MOUSEENTER
    MOUSEUP
    MOUSEDOWN
    SELECT
    SUBMIT
    SEARCH
    FOCUS
}

@enduml
