@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
interface IModule {
    + Identifier : Guid <<get>>
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}
!endsub
@enduml
