@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

interface IModule {
    + Identifier : Guid
    + IsEnabled : bool <<get>> <<set>>
    + Initialize() : void
}

interface ITransformingModule {

}

IModule <|-- ITransformingModule
@enduml
