@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
interface IModuleManager {
    + InitializeModules() : void
    + NotifyModulesOnSessionStart() : void
    + NotifyModulesOnSessionStop() : void
}
!endsub
@enduml
