@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
enum EventLabel {
    BUTTONCLICK,
    CLOSETAB,
    DOWNLOAD,
    HOVER,
    NAVIGATION,
    OPENTAB,
    SWITCHTAB,
    TEXTINPUT,
    TEXTSELECTION,
}
@enduml
