@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class MouseClickEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<MouseClickEvent>
    # <<override>> Enqueue(MouseClickEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<MouseClickEvent>" <|-- MouseClickEventProducer
@enduml
