@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class MouseMoveEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<MouseMoveEvent>
    # <<override>> Enqueue(MouseMoveEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<MouseMoveEvent>" <|-- MouseMoveEventProducer
@enduml
