@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class MouseMoveEventProducer {
    + StartCapture() : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
"DefaultEventQueue<T>" "    <MouseMoveEvent>" <|-- MouseMoveEventProducer
@enduml
