@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class ClipboardInteractEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<ClipboardInteractEvent>
    # <<override>> Enqueue(ClipboardInteractEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<ClipboardInteractEvent>" <|-- ClipboardInteractEventProducer
@enduml
