@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class WindowResizingEvent {
    + OldSize: System.Drawing.Size
    + NewSize: System.Drawing.Size
}
WindowEvent <|-- WindowResizingEvent

!include WindowEvent.puml
!endsub
@enduml
