@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class HookLibraryException {
    + <<create>> HookLibraryException()
    + <<create>> HookLibraryException(message: string)
}
!endsub
@enduml