@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class ButtonClickEvent {
    + Button : string <<get>> <<set>>
    + Href : string <<get>> <<set>>
}
abstract class WebBrowserEvent {
}

abstract class Event
WebBrowserEvent <|-- ButtonClickEvent
Event <|-- WebBrowserEvent
@enduml
