@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class ButtonClickEvent {
    + Button : string <<get>> <<set>>
    + URL: Uri
}
abstract class WebBrowserEvent {
    + TabID: Guid
    + CurrentURL: Uri
}


WebBrowserEvent <|-- ButtonClickEvent
Event <|-- WebBrowserEvent
@enduml
