@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class CloseTabEvent {
}
abstract class WebBrowserEvent {
    + TabID: Guid
    + CurrentURL: Uri
}
WebBrowserEvent <|-- CloseTabEvent
Event <|-- WebBrowserEvent
@enduml
