@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class CloseTabEvent {
}
abstract class WebBrowserEvent {
}
abstract class Event
WebBrowserEvent <|-- CloseTabEvent
Event <|-- WebBrowserEvent
@enduml
