@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class FileDownloadEvent {
    + MIMEType : string <<get>> <<set>>
    + FileURL: Uri <<get>> <<set>>
}
abstract class WebBrowserEvent {
    
}
abstract class Event
WebBrowserEvent <|-- FileDownloadEvent
Event <|-- WebBrowserEvent
@enduml
