@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class HoverEvent {
    + HoveredElement : string <<get>> <<set>>
}
abstract class WebBrowserEvent {
    + TabID : int <<get>> <<set>>
    + Deserialize(serialized:string) : void
    + Deserialize(parsed:JsonElement) : void
    + CurrentURL : Uri <<get>> <<set>>
}
abstract class Event

WebBrowserEvent <|-- HoverEvent
Event <|-- WebBrowserEvent
@enduml
