@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class HoverEvent {
    + HoveredElement : string <<get>> <<set>>
}
!endsub

WebBrowserEvent <|-- HoverEvent
!include WebBrowserEvent.puml
@enduml
