@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class OpenTabEvent {
}
abstract class WebBrowserEvent {
    + TabID: Guid
    + CurrentURL: Uri
}
WebBrowserEvent <|-- OpenTabEvent
Event <|-- WebBrowserEvent
@enduml
