@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class OpenTabEvent {
}
abstract class WebBrowserEvent {
    
}
abstract class Event
WebBrowserEvent <|-- OpenTabEvent
Event <|-- WebBrowserEvent
@enduml
