@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class SwitchTabEvent {
    + NewTabID: int <<get>><<set>>
}
abstract class WebBrowserEvent {

}
abstract class Event
WebBrowserEvent <|-- SwitchTabEvent
Event <|-- WebBrowserEvent
@enduml
