@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class SwitchTabEvent {
    + NewTabID: Guid
}
abstract class WebBrowserEvent {
    + TabID: Guid
    + CurrentURL: Uri
}
WebBrowserEvent <|-- SwitchTabEvent
Event <|-- WebBrowserEvent
@enduml
