@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class TextSelectionEvent {
    + SelectedText : string <<get>> <<set>>
}
abstract class WebBrowserEvent {

}
abstract class Event
WebBrowserEvent <|-- TextSelectionEvent
Event <|-- WebBrowserEvent
@enduml
