@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class KeyboardModule {
}

interface IModule {
    + Identifier : Guid
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}

IModule <|-- KeyboardModule
KeyboardModule --> "  KeyboardInteractEventProducer" KeyboardInteractEventProducer
@enduml
