@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class GlobalHook {
    + {static} IsActive : bool <<get>> <<set>>
    + {static} AddListener(callback: RetrieveMessageCallBack, types: NativeMethods.MessageType[])
    + {static} RemoveListener(callback: RetrieveMessageCallBack, types: NativeMethods.MessageType[])
    + {static} FreeLibrary()
}
!endsub
@enduml