@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0 
interface IWebBrowserEventObserver {
    + Notify(eventJson:JsonElement) : void
    + EnqueueFinished() : void
}
enum "EventLabel"

IWebBrowserEventObserver --> "HandledEventLabel" EventLabel
@enduml
