@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
!startsub default
class WindowFocusEventProducer {
    + StartCapture(nativeWinManagement : INativeWindowManagement) : void
    + StopCapture() : void
}
abstract class "DefaultEventQueue<T>" {
}
!endsub
"DefaultEventQueue<T>" "     <WindowFocusEvent>" <|-- WindowFocusEventProducer
@enduml
