@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class WindowFocusEventProducer {
    + StartCapture() : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
"DefaultEventQueue<T>" "     <WindowFocusEvent>" <|-- WindowFocusEventProducer
@enduml
