@startuml ProcessCommand
skinparam monochrome true
skinparam classAttributeIconSize 0
hide empty fields

!startsub default
class ProcessCommand {
    + Execute(options: ProcessOptions) : int
}
!endsub
ProcessCommand ... ProcessOptions : uses
ICLICommand <.. ProcessCommand : implements
IRecordingManager <-- "receiver" ProcessCommand
IDecoder <-- "decoder" ProcessCommand
@enduml