@startuml
class ValidateCommand {
    + ValidateCommand()
    + ValidateCommand(configurationManager:IConfigurationManager, consoleFormatter:IConsoleFormatter, bootstrapper:IBootstrapper)
    + Execute(options:ValidateOptions) : int
}
class "ICommand`1"<T> {
}
"ICommand`1" "<ValidateOptions>" <|-- ValidateCommand
@enduml
