@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class WindowStateChangedEventProducer {
    + StartCapture() : void
    + StopCapture() : void
}
class "DefaultEventQueue<T>" {
}
"DefaultEventQueue<T>" "      <WindowStateChangedEvent>" <|-- WindowStateChangedEventProducer
@enduml
