@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class WindowStateChangedEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<WindowStateChangedEvent>
    # <<override>> Enqueue(WindowStateChangedEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<WindowStateChangedEvent>" <|-- WindowStateChangedEventProducer
@enduml
