@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class WindowResizingEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<WindowResizingEvent>
    # <<override>> Enqueue(WindowResizingEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<WindowResizingEvent>" <|-- WindowResizingEventProducer
@enduml
