@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0

class WindowMovementEventProducer {
    + <<override>> GetEvents() : IAsyncEnumerable<WindowMovementEvent>
    # <<override>> Enqueue(WindowMovementEvent event) : void
}
class "EventQueue<T>" {
}
"EventQueue<T>" "<WindowMovementEvent>" <|-- WindowMovementEventProducer
@enduml
