@startuml CLI
skinparam monochrome true
skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../MORR.puml!CLI
'!includesub ../MORR.puml!CLI_INTERNAL
@enduml
