@startuml
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../MORR.puml!CORE
!includesub ../MORR.puml!CORE_INTERNAL
@enduml