@startuml CORE
skinparam monochrome true
skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../complete_diagram/MORR.puml!CORE
'!includesub ../complete_diagram/MORR.puml!CORE_INTERNAL
@enduml