@startuml MODULES_KEYBOARD
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../MORR.puml!MODULES_KEYBOARD
'!includesub ../MORR.puml!MODULES_KEYBOARD_INTERNAL
@enduml
