@startuml MODULES_CLIPBOARD
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!startsub default
package "CLIPBOARD" #BFBFBF {
    class ClipboardModule {
    
    }

    abstract class ClipboardEvent {
    
    }

    class ClipBoardInteractEvent {
        + Text : string <<get>> <<set>>
    }

    enum InteractionType {
        CLEAR
        COPY
        CUT
        PASTE
    }
}

'Clipboard
IModule <|.. ClipboardModule
Event <|-- ClipboardEvent
ClipboardEvent <|-- ClipBoardInteractEvent
ClipBoardInteractEvent --> "Interaction" InteractionType
ClipBoardInteractEvent +-- InteractionType
!endsub
@enduml
