@startuml MODULES_MOUSE
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../MORR.puml!MODULES_MOUSE
'!includesub ../MORR.puml!MODULES_MOUSE_INTERNAL
@enduml
