@startuml MODULES_CLIPBOARD
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../complete_diagram/MORR.puml!MODULES_CLIPBOARD
'!includesub ../complete_diagram/MORR.puml!MODULES_CLIPBOARD_INTERNAL
@enduml
