@startuml TRANSCODING
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!includesub ../complete_diagram/MORR.puml!TRANSCODING
!includesub ../complete_diagram/MORR.puml!TRANSCODING_INTERNAL
!includesub ../complete_diagram/MORR.puml!TRANSCODING_MPEG_INTERNAL
!includesub ../complete_diagram/MORR.puml!EXCEPTIONS
@enduml
