@startuml UI
skinparam monochrome true
'skinparam linetype ortho
skinparam classAttributeIconSize 0

left to right direction
hide empty fields
!startsub default
package "UI" #E6E6E6 {
    class ErrorDialog <<partial>> {
        + ErrorDialog(errorMessage:string)
        + ErrorMessage : string <<get>>
    }

    class InformationDialog <<partial>> {
        + InformationDialog()
    }

    class SaveDialog <<partial>> {
        + SaveDialog()
    }

    class ApplicationViewModel {
        + ApplicationViewModel()
        + IsRecording : bool <<get>> <<set>>
    }
    
    class NotifyIcon {
        + NotifyIcon()
        + Tooltip : string <<get>> <<set>>
        + CommandParameter : object <<get>> <<set>>
    }
    
    class RelayCommand {
        + RelayCommand(execute:Action<object>, canExecute:Predicate<object>?)
        + CanExecute(parameter:object) : bool
        + Execute(parameter:object) : void
    }

    interface ICommand {

    }

    class ContextMenu {

    }

    class ImageSource {

    }

    class App <<partial>> {

    }        
}

' UI
ApplicationViewModel --> "1" IRecordingManager : uses
ApplicationViewModel o--> "n" ICommand
App --> "1" ApplicationViewModel
ApplicationViewModel o-> SaveDialog
ApplicationViewModel o-> ErrorDialog
ApplicationViewModel o-> InformationDialog
App o-> NotifyIcon
NotifyIcon --> "IconSource" ImageSource
NotifyIcon --> "Command" ICommand
NotifyIcon --> "ContextMenu" ContextMenu
ICommand <|.. RelayCommand
!endsub
@enduml
