@startuml(id=default)
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "DefaultEventQueue<T: Event>" {
    # <<create>> DefaultEventQueue(bufferCapacity: int, maxConsumers: uint?)
}

abstract class "DefaultEncodeableEventQueue<T: Event>" {
    # <<create>> DefaultEncodeableEventQueue(bufferCapacity: int)
}

abstract class "DefaultDecodeableEventQueue<T: Event>" {
    # <<create>> DefaultDecodeableEventQueue(bufferCapacity: int, maxConsumers: uint?)
}

abstract class "NonDeserializableEventQueue<T: Event>" {
    # <<create>> NonDeserializableEventQueue(bufferCapacity: int, maxConsumers: uint?)
}
!endsub
@enduml