@startuml(id=default)
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "DefaultEventQueue<T: Event>" {
    # <<create>> DefaultEventQueue(bufferCapacity: int, maxConsumers: uint?)
}

abstract class "DefaultEncodableEventQueue<T: Event>" {
    # <<create>> DefaultEncodableEventQueue(bufferCapacity: int)
}

abstract class "DefaultDecodableEventQueue<T: Event>" {
    # <<create>> DefaultDecodableEventQueue(bufferCapacity: int, maxConsumers: uint?)
}

abstract class "NonDeserializableEventQueue<T: Event>" {
    # <<create>> NonDeserializableEventQueue(bufferCapacity: int, maxConsumers: uint?)
}
!endsub
@enduml