@startuml(id=default)
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "BaseEventQueue<TEvent>" {
    + IsClosed : bool <<get>>
    + GetEvents() : IAsyncEnumerable<TEvent>
    + Enqueue(@event:TEvent) : void
    + Open() : void
    + Close() : void
}
!endsub 
@enduml
