@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "BaseEventQueue<TEvent> where TEvent : Event" as BaseEventQueue {
    + IsClosed : bool
    + GetEvents() : IAsyncEnumerable<TEvent>
    + Enqueue()
    + Open()
    + Close()
}
!endsub
@enduml