@startuml(id=default)
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "DefaultEncodeableEventQueue<T>" {
    
}
interface "IEncodableEventQueue<T>"
abstract class "BaseEventQueue<T>"
"IEncodableEventQueue<T>" <|-- "DefaultEncodeableEventQueue<T>"
"BaseEventQueue<T>" <|-- "DefaultEncodeableEventQueue<T>"
!endsub
@enduml