@startuml(id=default)
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
abstract class "DefaultEventQueue<T>" {

}
abstract class "SupportDeserializationEventQueue<T>"
"SupportDeserializationEventQueue<T>" <|-- "DefaultEventQueue<T>"
!endsub
@enduml

