@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

abstract class "EventQueue<T> where T : Event" {
    + StorageStrategy : IEventQueueStorageStrategy<T> <<get>> <<set>>
    + {abstract} GetEvents() : IAsyncEnumerable<T>
    # {abstract} Enqueue(T @event) : void
}

interface "IReadOnlyEventQueue<out T> where T : Event" {
    GetEvents() : IAsyncEnumerable<T>
}

"IReadOnlyEventQueue<out T> where T : Event" <|-- "EventQueue<T>"
@enduml
