@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

abstract class "EventQueue<T>" {
    
}
class "IReadOnlyEventQueue<T>" {
    + {abstract} GetEvents() : IAsyncEnumerable<T>
    # {abstract} Enqueue(T @event) : void
}

"IReadOnlyEventQueue<T>" <|-- "EventQueue<T>"
@enduml
