@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

interface "IReadOnlyEventQueue<T>"

abstract class "EventQueue<T>" {
    + {abstract} GetEvents() : IAsyncEnumerable<T>
    # {abstract} Enqueue(T @event) : void
}

"IReadOnlyEventQueue<T>" <|-- "EventQueue<T>"
@enduml
