@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

!startsub default
interface "IReadOnlyEventQueue<T: Event>" {
    + EventType: Type
    + GetEvents() : IAsyncEnumerable<T: Event>
}
!endsub
@enduml