@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
interface "ISupportDeserializationEventQueue<T: Event>" {
    + EventType: Type
    + Enqueue(event: object): void
}
!endsub
@enduml