@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class "KeepAllStorageStrategy<T> where T : Event" {
    + GetEvents() : IAsyncEnumerable<T>
    + Enqueue(T @event) : void
}

interface "IEventQueueStorageStrategy<T> where T : Event" {
    + GetEvents() : IAsyncEnumerable<T>
    + Enqueue(T @event) : void
}

"IEventQueueStorageStrategy<T> where T : Event" <|-- "KeepAllStorageStrategy<T> where T : Event"
@enduml
