name: Build + Test

on:
  push:
    branches: 
      - master
      - develop
  pull_request:
    branches: 
      - master
      - develop

jobs:
  dotNET-Core:
    name: Build .NET Core
    runs-on: windows-latest

    steps:
    - name: Pull branch
      uses: actions/checkout@v1
    
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '3.1.100'
        
    - name: Remove WebExtension from Runner solution
      run: dotnet sln application/MORR.sln remove application/BrowserExtension/BrowserExtension.njsproj

    - name: Remove HoobLibrary from Runner solution (temporary)
      run: dotnet sln application/MORR.sln remove application/Common/HookLibrary/HookLibrary.vcxproj

    - name: Clean
      run: dotnet clean application/MORR.sln --nologo
    
    - name: Build
      run: dotnet build application/MORR.sln --configuration Release --nologo
    
    - name: Run tests
      run: dotnet test application/MORR.sln -t

  TypeScript:
    name: Build Typescript
    runs-on: windows-latest

    steps:
      - name: Pull branch
        uses: actions/checkout@v1
      
      - name: Install
        working-directory: ./application/BrowserExtension
        run: npm install
    
      - name: Clean
        working-directory: ./application/BrowserExtension
        run: npm run clean
      
      - name: Build
        working-directory: ./application/BrowserExtension
        run: npm run build
      
      - name: Test
        working-directory: ./application/BrowserExtension
        run: npm run testcoverage
        
