@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class MouseModule {
}

interface IModule {
    + Identifier : System.Guid
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}
!endsub
IModule <|-- MouseModule
MouseModule --> "  MouseScrollEventProducer" MouseScrollEventProducer
MouseModule --> " MouseMoveEventProducer " MouseMoveEventProducer
MouseModule --> "   MouseClickEventProducer" MouseClickEventProducer
@enduml
