@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0

class MouseModule {
}

ICollectingModule <|-- MouseModule

interface IModule {
    + Identifier : Guid
    + IsEnabled : bool <<get>> <<set>>
    + Initialize() : void
}

IModule <|-- ICollectingModule
@enduml
