@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class MouseModule {
}

interface IModule {
    + Identifier : System.Guid
    + IsActive : bool <<get>> <<set>>
    + Initialize() : void
}

!endsub
IModule <|-- MouseModule
MouseModule ..> MouseMoveEventProducer : "uses"
MouseModule ..> MouseClickEventProducer : "uses"
MouseModule ..> MouseScrollEventProducer : "uses"
MouseModule ..> MouseModuleConfiguration : "uses"
@enduml
