@startuml
skinparam monochrome true
skinparam ClassAttributeIconSize 0
class MouseModuleConfiguration {
    + SamplingRateInHz : uint <<get>> <<set>>
    + Threshold : int <<get>> <<set>>
    + Parse(configuration:RawConfiguration) : void
}
IConfiguration <|-- MouseModuleConfiguration
@enduml
