@startuml
class NotifyIcon {
    + NotifyIcon()
    + Tooltip : string <<get>> <<set>>
    + CommandParameter : object <<get>> <<set>>
    + Dispose() : void
}
Control <|-- NotifyIcon
IDisposable <|-- NotifyIcon
NotifyIcon o-> "CommandProperty" DependencyProperty
NotifyIcon o-> "CommandParameterProperty" DependencyProperty
NotifyIcon o-> "ContextMenuProperty" DependencyProperty
NotifyIcon o-> "IconSourceProperty" DependencyProperty
NotifyIcon o-> "TooltipProperty" DependencyProperty
NotifyIcon --> "IconSource" ImageSource
NotifyIcon --> "Command" ICommand
NotifyIcon --> "ContextMenu" ContextMenu
@enduml
