@startuml
skinparam monochrome true
skinparam classAttributeIconSize 0
!startsub default
class NotifyIcon {
    + <<create>> NotifyIcon()
    + Tooltip : string <<get>> <<set>>
    + CommandParameter : object <<get>> <<set>>
    + Dispose() : void
}
!endsub
Control <|-- NotifyIcon
IDisposable <|.. NotifyIcon
/'NotifyIcon o-> "CommandProperty" DependencyProperty
NotifyIcon o-> "CommandParameterProperty" DependencyProperty
NotifyIcon o-> "ContextMenuProperty" DependencyProperty
NotifyIcon o-> "IconSourceProperty" DependencyProperty
NotifyIcon o-> "TooltipProperty" DependencyProperty'/
NotifyIcon --> "Command" ICommand
NotifyIcon --> "ContextMenu" ContextMenu
@enduml